# Generated by Django 5.0.7 on 2024-10-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tglink',
            field=models.URLField(default='http://example.com'),
        ),
    ]
